### ISSUE TITLE
Static wrapping in addition to dynamic wrapping

### ISSUE THREAD

**Issue by matthijskooijman** [hedayat/powerfake#3]
One thing I think might be interesting to support is static wrapping. Right now, only "dynamic" wrapping is supported: You declare some function as wrapped, and you can replace it at runtime. With "static wrapping", I mean to replace some function with some wrapper function unconditionally (provided the object containing the wrapping is included in the link and the needed linker arguments are given, of course).

I can imagine cases where, when running unit tests, you *always* want to replace some functions since they'll *never* do something meaningful in a test environment. You can do this by just replacing them at the top of main, but doing it implicitly allows a more declarative syntax for this.

Another case for this could be when you want to use Powerfake in a lighter mode, where you just need to replace some functions. You do not need to full runtime support, but do want to use Powerfake's machinery for figuring out the right wrapper filenames and linker commandline options.

One challenge here is to support actual wrapping: How does the replacement function know the name to use for the original function? I can imagine passing a pointer to it as an extra argument to the wrapper function, or maybe passing the name to the macro that sets this up (so then the user decides the name, and Powerfake must make sure it's set up as an alias of some sort to the real function).

This is not anything critical, but something that seemed like an interesting idea to share and not forget :-)

**Comment by hedayat** [comment]
To be honest, I'm not much interested in this; unless it can provide some possibilities not available right now: e.g. if they allow intercepting calls in the same TU for example using weak symbols. And note that even if you always want to replace a function, it is likely that you need a different implementation for each test.

Because I think extending API is not good. IMHO, less API means simpler usage as there are less things to remember and decide. I prefer to use a global fixture for that. And I think a single extra MakeFake() call does not worth adding a new wrap macro. 

And I just remembered something: I really designed powerfake to do just the low level process of replacing functions, with the goal that it'll be integrated in higher level mocking libraries. Currently, it has FakeIt integration, which provides very handy tools for mocking as some examples are also provided in the sample/ code. Unless there is a reason to not use that integration, I think it is better for most users to use PowerFake through its FakeIt integration rather than using it directly. And in that case, static wrapping is useless as you don't define any replacement functions at all and use FakeIt facilities to mock the function as desired in each test.

**Comment by hedayat** [comment]
I close this issue for now. Specially as there is also google mock integration now, and I didn't find much usefulness in the idea. But, if there is more interest, it can be opened again.
