### ISSUE TITLE
How do I fake this method?

### ISSUE THREAD

**Issue by mbandu** [hedayat/powerfake#4]
Hi,
How do i fake this method?
void cli_print(struct cli_def *cli, const char *format, ...);

throw error when i do like this...
auto offk = PowerFake::MakeFake<void (struct cli_def *cli, const char *format, ...)>(cli_print,
        [](void) { cout << "Fake called for overloaded(float)" << endl; }
    );

error message:
In instantiation of ‘PowerFake::FakePtr PowerFake::MakeFake(Signature*, Functor) [with Signature = void(cli_def*, const char*, ...); Functor = C_A_T_C_H_T_E_S_T_6()::<lambda()>; PowerFake::FakePtr = std::unique_ptr<PowerFake::internal::FakeBase>]’:
test_libcli_helper.cpp:59:5:   required from here
/usr/local/include/powerfake/powerfake.h:1097:17: error: invalid use of incomplete type ‘struct PowerFake::internal::func_cv_processor<void (*)(cli_def*, const char*, ...)>’
 1097 |     return std::make_unique<internal::Fake<FuncType>>(
      |            ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from test_libcli_helper.cpp:6:
/usr/local/include/powerfake/powerfake.h:281:8: note: declaration of ‘struct PowerFake::internal::func_cv_processor<void (*)(cli_def*, const char*, ...)>’
  281 | struct func_cv_processor;
      |        ^~~~~~~~~~~~~~~~~
In file included from test_libcli_helper.cpp:6:
/usr/local/include/powerfake/powerfake.h:1098:55: error: invalid use of incomplete type ‘struct PowerFake::internal::func_cv_processor<void (*)(cli_def*, const char*, ...)>’
 1098 |             internal::Wrapper<FuncType>::WrapperObject(func_ptr), f);
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~

Thank you so much.

Bandu

**Comment by hedayat** [comment]
Hi, and thank you for reporting the bug.

I found that variadic functions are not supported currently. I've experimented a little and it seems that support for them can be added. However, it is very likely that you'll lose access to the original function by wrapping a variadic function: you can no longer call the original function in your tests, because it seems that there is no way to forward variadic arguments from one function to the other. Although, there can be compiler specific ways to do it. I might add support for specific compilers.

**Comment by mbandu** [comment]
I won’t call original function again in the test.

Thank you!

Bandu
***@***.***

**Comment by hedayat** [comment]
This is hopefully fixed now. Note that the fake function should receive `va_list` rather than `...` for variadic params.
